name: New Idea
description: Submit a new idea to share with the IdeaPool community.
title: "[Idea-1]: "
labels: ["idea-1", "triage"]
projects: ["ideapool/1"]
assignees:
  - learn-hub
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing a new idea! IdeaPool is a space for educators and students to share creative and useful ideas, such as examples or applications of mathematical concepts, that enhance understanding and engagement.

  - type: input
    id: title
    attributes:
      label: Idea Title
      description: Provide a concise title for your idea.
      placeholder: Enter a brief and descriptive title for your idea.
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Relevant/Source Link (video, book, etc.)
      description: Share any relevant link (optional).
      placeholder: Include a URL if relevant.

  - type: input
    id: link-section
    attributes:
      label: Specific Section of the Source (e.g., start/end time for videos or page numbers for books)
      description: Provide specific parts of the source (optional). 
      placeholder: Include time range or page numbers if relevant.

  - type: textarea
    id: summary
    attributes:
      label: Summary/Synopsis
      description: Provide a short summary of the core idea.
      placeholder: Give a quick overview of the core idea/concept.
    validations:
      required: true

  - type: textarea
    id: main-idea
    attributes:
      label: Main Idea
      description: Describe the main idea or concept in detail.
      placeholder: Explain the idea thoroughly. You may include text, images, or any helpful resources.
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Idea Type
      description: Select the type of idea you're submitting.
      options:
        - Application
        - Sense-making
        - Definition
        - Explanation
        - Analogy
        - In-depth explanation
        - Problem/Question
        - Graph
        - Joke
        - Concept map
        - Level system
        - Comic references
        - Thematic approach
        - Topic-based thesaurus
        - Engagement elements
        - Poem
        - Riddle
        - Funny clip
        - Meme
        - GIF
        - Movie
        - Quiz
        - Question
        - Easter egg
        - Plot twists
        - Call for help
        - Sub-section
        - Disambiguation guide
        - Pain point

  - type: dropdown
    id: subject-area
    attributes:
      label: Main Educational Subject Area
      description: Select the main educational subject
      options:
        - math--arithmetic
        - math--algebra
        - math--geometry
        - math--trigonometry
        - math--calculus
        - math--statistics
        - math--probability
        - math--number-theory
        - math--linear-algebra
        - math--differential-equations
        - math--discrete-mathematics
        - math--topology
        - math--mathematical-logic
        - math--complex-analysis
        - math--real-analysis
        - math--numerical-analysis
        - math--mathematical-modeling
        - math--set-theory
        - math--game-theory
        - math--optimization
        - physics--classical-mechanics
        - physics--thermodynamics
        - physics--electromagnetism
        - physics--optics
        - physics--quantum-mechanics
        - physics--relativity
        - physics--particle-physics
        - physics--astrophysics
        - physics--nuclear-physics
        - physics--condensed-matter
        - physics--fluid-dynamics
        - physics--atomic-physics
        - physics--statistical-mechanics
        - physics--plasma-physics
        - physics--wave-theory
        - physics--acoustics
        - physics--biophysics
        - physics--geophysics
        - physics--quantum-field-theory
        - physics--experimental-physics
        - chemistry--organic-chemistry
        - chemistry--inorganic-chemistry
        - chemistry--physical-chemistry
        - chemistry--analytical-chemistry
        - chemistry--biochemistry
        - chemistry--theoretical-chemistry
        - chemistry--environmental-chemistry
        - chemistry--materials-science
        - chemistry--polymer-chemistry
        - chemistry--supramolecular-chemistry
        - chemistry--nanochemistry
        - chemistry--industrial-chemistry
        - chemistry--quantum-chemistry
        - chemistry--electrochemistry
        - chemistry--chemical-engineering
        - chemistry--spectroscopy
        - chemistry--crystallography
        - chemistry--surface-chemistry
        - chemistry--photochemistry
        - chemistry--organometallic-chemistry
        - biology--cell-biology
        - biology--genetics
        - biology--molecular-biology
        - biology--evolutionary-biology
        - biology--ecology
        - biology--microbiology
        - biology--biochemistry
        - biology--anatomy
        - biology--physiology
        - biology--developmental-biology
        - biology--neuroscience
        - biology--immunology
        - biology--botany
        - biology--zoology
        - biology--marine-biology
        - biology--environmental-biology
        - biology--virology
        - biology--bioinformatics
        - biology--bioengineering
        - biology--astrobiology
        - computer--programming
        - computer--algorithms
        - computer--data-structures
        - computer--operating-systems
        - computer--databases
        - computer--computer-networks
        - computer--artificial-intelligence
        - computer--machine-learning
        - computer--computer-graphics
        - computer--human-computer-interaction
        - computer--software-engineering
        - computer--theory-of-computation
        - computer--cybersecurity
        - computer--computer-architecture
        - computer--distributed-systems
        - computer--cloud-computing
        - computer--web-development
        - computer--mobile-computing
        - computer--computer-vision
        - computer--natural-language-processing

  - type: dropdown
    id: education-level
    attributes:
      label: Education Level (difficulty level)
      description: Select the appropriate education level for this idea.
      options:
        - pre-elementary and above
        - elementary and above
        - middle school and above
        - high school and above
        - college and above
        - bachelor's and above
        - master's and above
        - professional/PhD and above

  - type: textarea
    id: main-education-subjects
    attributes:
      label: Educational Sub-Category
      description: Specify the sub-categories of the main educational subjects that this idea applies to.
      placeholder: List the relevant sub-categories for this idea.

  - type: textarea
    id: main-topics
    attributes:
      label: Main Topics
      description: List the main topics that describe the context of this idea.
      placeholder: Provide the core topics associated with this idea.

  - type: textarea
    id: other-related-topics
    attributes:
      label: Other Related Topics
      description: Mention any other topics this idea connects with.
      placeholder: List related topics or areas of interest.

  - type: textarea
    id: faq
    attributes:
      label: FAQ
      description: Provide common questions and answers related to the topic. This section helps address typical concerns or doubts that may arise.
      placeholder: Enter frequently asked questions and their corresponding answers here.

  - type: textarea
    id: experiential-scenarios
    attributes:
      label: Experiential Scenarios
      description: Describe real-world scenarios or challenges where the concept can be applied, allowing students to engage in practical problem-solving.
      placeholder: List and explain experiential scenarios that involve applying the concept to real-world problems or challenges.

  - type: textarea
    id: comments-notes
    attributes:
      label: Comments/Notes
      description: Share any additional comments or insights.
      placeholder: Provide any additional notes or feedback.

  - type: input
    id: overall-score
    attributes:
      label: Overall Score
      description: Rate the overall quality of this idea (1-10).
      placeholder: Enter a rating from 1 to 10.

  - type: input
    id: usefulness-score
    attributes:
      label: Usefulness Score
      description: Rate how useful this idea is (1-10).
      placeholder: Enter a rating from 1 to 10.

  - type: input
    id: ease-of-follow-score
    attributes:
      label: Ease of Understanding Score
      description: Rate how easy it is to follow this idea (1-10).
      placeholder: Enter a rating from 1 to 10.

  - type: input
    id: contact
    attributes:
      label: Contact Information
      description: Provide your contact details in case we need more information.
      placeholder: ex. your.email@example.com

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct Agreement
      description: By submitting this idea, you agree to follow our [Code of Conduct](https://example.com).
      options:
        - label: I agree to follow this project's Code of Conduct
