name: New Idea
description: Submit a new idea to share with the IdeaPool community.
title: "[Idea-1]: "
labels: ["idea-1", "triage"]
projects: ["ideapool/1"]
assignees:
  - learn-hub
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing a new idea! IdeaPool is a space for educators and students to share creative and useful ideas, such as examples or applications of mathematical concepts, that enhance understanding and engagement.

  - type: input
    id: title
    attributes:
      label: Idea Title
      description: Provide a concise title for your idea.
      placeholder: Enter a brief and descriptive title for your idea.
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Relevant Link
      description: Share any relevant link (optional).
      placeholder: Include a URL if relevant.

  - type: textarea
    id: main-idea
    attributes:
      label: Main Idea/Synopsis
      description: Describe the main idea or concept in detail.
      placeholder: Explain the idea thoroughly. You may include text, images, or any helpful resources.
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Idea Type
      description: Select the type of idea you're submitting.
      options:
        - application
        - definition
        - explanation
        - analogy
        - deep explanation
        - problem/question
        - graph
        - joke
        - concept map
        - level system
        - comic references
        - theme (approach)
        - topic-based thesaurus
        - engagement aspects
        - poem
        - riddle
        - funny clip
        - meme
        - gif
        - movie
        - quiz
        - question
        - easter egg
        - twists
        - ask for help
        - sub-section
        - disambiguity guide
        - pain

  - type: textarea
    id: main-education-subjects
    attributes:
      label: Educational Subjects
      description: Specify the main educational subjects this idea can be used for.
      placeholder: List the subjects relevant to this idea.

  - type: textarea
    id: main-topics
    attributes:
      label: Main Topics
      description: List the main topics that describe the context of this idea.
      placeholder: Provide the core topics associated with this idea.

  - type: textarea
    id: other-related-topics
    attributes:
      label: Other Related Topics
      description: Mention any other topics this idea connects with.
      placeholder: List related topics or areas of interest.

  - type: textarea
    id: comments-notes
    attributes:
      label: Comments/Notes
      description: Share any additional comments or insights.
      placeholder: Provide any additional notes or feedback.

  - type: input
    id: overall-score
    attributes:
      label: Overall Score
      description: Rate the overall quality of this idea (1-10).
      placeholder: Enter a rating from 1 to 10.

  - type: input
    id: usefulness-score
    attributes:
      label: Usefulness Score
      description: Rate how useful this idea is (1-10).
      placeholder: Enter a rating from 1 to 10.

  - type: input
    id: ease-of-follow-score
    attributes:
      label: Ease of Understanding Score
      description: Rate how easy it is to follow this idea (1-10).
      placeholder: Enter a rating from 1 to 10.

  - type: input
    id: contact
    attributes:
      label: Contact Information
      description: Provide your contact details in case we need more information.
      placeholder: ex. your.email@example.com

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct Agreement
      description: By submitting this idea, you agree to follow our [Code of Conduct](https://example.com).
      options:
        - label: I agree to follow this project's Code of Conduct
